ci: mudança no código de validação dos commits

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -13,14 +13,15 @@ jobs:
       - uses: actions/checkout@v4
       - run: |
           echo "Validating commit messages..."
-          REGEX="^((Merge.*)|(Revert.*)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*))"
-          COMMIT_MSGS=$(git log --format=%B ${{ github.event.before }}..${{ github.event.after }})
-          echo "$COMMIT_MSGS" | while read -r COMMIT_MSG; do
-            if ! echo "$COMMIT_MSG" | grep -Eq "$REGEX"; then
-              echo "Commit message does not follow the convention: $COMMIT_MSG"
-              exit 1
-            fi
-          done
+          REGEX="^((Merge[ a-z-]* branch.*)|(Revert*)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*))"
+          FILE=`cat $1` # File containing the commit message
+          echo "Commit Message: ${FILE}"
+          if ! [[ $FILE =~ $REGEX ]]; then
+            echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard.​"
+            exit 1
+          else
+            echo >&2 "Valid commit message."
+          fi
 
   build:
     runs-on: ubuntu-latest
